[package]
name = "workspace-svc"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../../../crates/shared" }
llama_shared = { path="../llama_shared"}
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
diesel.workspace = true
dotenv.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
chrono.workspace = true
jsonwebtoken = "9"
tower-http = { version = "0.5", features = ["cors", "fs"] }
mime_guess = "2"
base64 = "0.21" 
reqwest = { version = "0.11", features = ["stream", "json"] }
futures = "0.3" 
async-stream = "0.3" 
bytes = "1" 
serde_yaml = "0.9"
tokio-stream = { version="0.1.18",features=["full"] }
futures-util = "0.3.32"
futures-core = "0.3.32"

[[bin]]
name = "workspace-svc"
path = "src/main.rs"
