[package]
name = "mcp-provider-svc"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
axum = { version = "0.7", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
rmcp = { version = "1.6.0" ,features=["server","schemars","macros","server-side-http","transport-streamable-http-server-session","transport-streamable-http-server","transport-async-rw","transport-worker"]}

tokio-stream = { version="0.1.18",features=["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1"
redis = "0.23"
reqwest = { version = "0.11", features = ["stream", "json"] }
lazy_static = "1.4"
tower-http = { version = "0.5", features = ["cors"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
uuid = { version = "1", features = ["v4"] }
async-trait = "0.1"

[[bin]]
name = "mcp-provider-svc"
path = "src/main.rs"
